workspace:
  base: /go
  path: src/github.com/cblomart/registry-token-ldap

# clone with tags
clone:
  git:
    image: plugins/git
    tags: true

pipeline:
  buildamd64:
    name: build amd64
    image: golang:latest
    commands:
    - mkdir -p releases/amd64
    - go build -o ./releases/amd64/registry-token-ldap .