workspace:
  base: /go
  path: src/github.com/cblomart/registry-token-ldap

# clone with tags
clone:
  git:
    image: plugins/git
    tags: true

pipeline:
  buildamd64:
    name: build amd64
    group: build
    image: golang:latest
    environment:
    - CGO=0
    - GOOS=linux
    - GOARCH=amd64
    commands:
    - mkdir -p releases/amd64
    - go build -ldflags '-s -w' -a -o ./releases/amd64/registry-token-ldap .
  buildarm:
    name: build arm
    group: build
    image: golang:latest
    environment:
    - CGO=0
    - GOOS=linux
    - GOARCH=arm
    - GOARM=5
    commands:
    - mkdir -p releases/arm
    - go build -ldflags '-s -w' -a -o ./releases/arm/registry-token-ldap .
    when:
      event: [ tag ]