jwscert: /etc/registry-token-ldap/cert.crt
jwskey: /etc/registry-token-ldap/cert.key
ldapserver: ad.contoso.com
ldapbase: "DC=contoso,DC=com"
defaultdomain: CONTOSO
rules:
  # Admin can do all
  - group: "AdminGroup"
    match: ".+"
    actions: [ "push", "pull" ]
  # Users can do all on their repo
  - match: "${user}/.+"
    actions: [ "push", "pull" ]
  # Everybody can pull
  - match: ".+"
    actions: [ "pull" ]